version: '3.8'

name: eduspace_experiments
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_experiments
    restart: always
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data_experiments:/var/lib/mysql

volumes:
  mysql_data_experiments:

